/**
 * Real design work supplied to fill the /graphics canvas while the admin
 * hasn't created any rows in the live database yet. Aspect ratios are
 * measured from the actual source files (not guessed) so the masonry layout
 * in `masonry.ts` can size each card to match its image instead of cropping
 * it into a generic bucket.
 */
export interface GraphicsPlaceholderImage {
  file: string
  aspect: number
}

export const GRAPHICS_PLACEHOLDER_IMAGES: readonly GraphicsPlaceholderImage[] = [
  { file: '/graphics/graphics-01.png', aspect: 0.8 },
  { file: '/graphics/graphics-02.png', aspect: 1 },
  { file: '/graphics/graphics-03.jpg', aspect: 1 },
  { file: '/graphics/graphics-04.jpg', aspect: 1 },
  { file: '/graphics/graphics-05.png', aspect: 0.8 },
  { file: '/graphics/graphics-06.png', aspect: 1 },
  { file: '/graphics/graphics-07.png', aspect: 0.8 },
  { file: '/graphics/graphics-08.jpg', aspect: 1 },
  { file: '/graphics/graphics-09.jpg', aspect: 1 },
  { file: '/graphics/graphics-10.png', aspect: 0.8 },
  { file: '/graphics/graphics-11.png', aspect: 1.3333 },
  { file: '/graphics/graphics-12.png', aspect: 0.8 },
  { file: '/graphics/graphics-13.png', aspect: 0.8 },
  { file: '/graphics/graphics-14.png', aspect: 0.8 },
  { file: '/graphics/graphics-15.png', aspect: 0.8 },
  { file: '/graphics/graphics-16.png', aspect: 1 },
  { file: '/graphics/graphics-17.png', aspect: 0.8 },
  { file: '/graphics/graphics-18.png', aspect: 1 },
  { file: '/graphics/graphics-19.png', aspect: 1.3998 },
  { file: '/graphics/graphics-20.png', aspect: 0.8 },
  { file: '/graphics/graphics-21.jpg', aspect: 1.796 },
  { file: '/graphics/graphics-22.png', aspect: 0.8 },
  { file: '/graphics/graphics-23.png', aspect: 1 },
  { file: '/graphics/graphics-24.png', aspect: 0.8 },
  { file: '/graphics/graphics-25.jpeg', aspect: 0.8 },
  { file: '/graphics/graphics-26.png', aspect: 0.8 },
  { file: '/graphics/graphics-27.png', aspect: 0.8 },
  { file: '/graphics/graphics-28.jpg', aspect: 1 },
  { file: '/graphics/graphics-29.png', aspect: 0.8 },
  { file: '/graphics/graphics-30.png', aspect: 0.8 },
  { file: '/graphics/graphics-31.png', aspect: 1 },
  { file: '/graphics/graphics-32.png', aspect: 1.9108 },
  { file: '/graphics/graphics-33.png', aspect: 0.8 },
  { file: '/graphics/graphics-34.jpg', aspect: 0.8 },
  { file: '/graphics/graphics-35.png', aspect: 1 },
  { file: '/graphics/graphics-36.jpg', aspect: 1 },
  { file: '/graphics/graphics-37.jpg', aspect: 1.7778 },
  { file: '/graphics/graphics-38.png', aspect: 1 },
  { file: '/graphics/graphics-39.jpg', aspect: 1 },
  { file: '/graphics/graphics-40.png', aspect: 0.8 },
  { file: '/graphics/graphics-41.png', aspect: 1 },
  { file: '/graphics/graphics-42.png', aspect: 0.8 },
  { file: '/graphics/graphics-43.png', aspect: 1 },
  { file: '/graphics/graphics-44.png', aspect: 0.8 },
  { file: '/graphics/graphics-45.png', aspect: 1 },
  { file: '/graphics/graphics-46.png', aspect: 0.8 },
  { file: '/graphics/graphics-47.jpg', aspect: 1 },
  { file: '/graphics/graphics-48.jpeg', aspect: 0.8 },
  { file: '/graphics/graphics-49.jpg', aspect: 1 },
  { file: '/graphics/graphics-50.png', aspect: 1.9108 },
  { file: '/graphics/graphics-51.jpeg', aspect: 1 },
  { file: '/graphics/graphics-52.jpg', aspect: 1 },
  { file: '/graphics/graphics-53.png', aspect: 1.9108 },
  { file: '/graphics/graphics-54.png', aspect: 0.8 },
  { file: '/graphics/graphics-55.jpg', aspect: 1 },
  { file: '/graphics/graphics-56.png', aspect: 0.8 },
  { file: '/graphics/graphics-57.png', aspect: 0.8 },
  { file: '/graphics/graphics-58.jpg', aspect: 0.8 },
  { file: '/graphics/graphics-59.png', aspect: 0.8 },
  { file: '/graphics/graphics-60.png', aspect: 0.8 },
  { file: '/graphics/graphics-61.png', aspect: 1 },
  { file: '/graphics/graphics-62.png', aspect: 0.8 },
  { file: '/graphics/graphics-63.png', aspect: 1 },
  { file: '/graphics/graphics-64.png', aspect: 0.8 },
  { file: '/graphics/graphics-65.jpg', aspect: 0.8 },
  { file: '/graphics/graphics-66.png', aspect: 0.8 },
  { file: '/graphics/graphics-67.png', aspect: 0.8 },
] as const
